version: "3.8"

networks:
  rag-net:
    driver: bridge

services:
  # 后端 Flask 服务
  backend_xiao_zhi_ai:
    build:
      context: ./RAG_PROJECT
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - rag-net

  # Nginx 反向代理，挂载前端静态资源和 nginx 配置
  nginx_xiao_zhi_ai:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./RAG_FRONTEND/dist:/usr/share/nginx/html/xiao-zhi-ai:ro
    depends_on:
      - backend_xiao_zhi_ai
    networks:
      - rag-net
